server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/tinyhacknews
        username: tiny-hacknews
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
