server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/tinyhacknews
        username: tiny-hacknews
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
        host: localhost
        port: 6379
#        password: your_redis_password  # 如果有密码的话
        database: 0
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                min-idle: 0
                max-wait: -1ms
logging:
    level:
        org:
            zalando:
                logbook: TRACE

user:
    dir: /Users/adl/repos/tinyhacknews


mybatis-plus:
    global-config:
        db-config:
            logic-delete-field: is_deleted # 全局逻辑删除字段名
            logic-delete-value: 1 # 逻辑已删除值
            logic-not-delete-value: 0 # 逻辑未删除值

jwt:
    secret-key: 6218afc7dc5353dbad602c8f3227ab06dfa9e6c9471c2449fa132d7bc7e959ab

springdoc:
    swagger-ui:
        path: /api/v1/swagger/swagger-ui.html
    api-docs:
        path: /api/v1/swagger/api-docs


