server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/tinyhacknews
        username: tiny-hacknews
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver

logging:
    level:
        org:
            zalando:
                logbook: TRACE

user:
    dir: /Users/adl/repos/tinyhacknews


mybatis-plus:
    global-config:
        db-config:
            logic-delete-field: is_deleted # 全局逻辑删除字段名
            logic-delete-value: 1 # 逻辑已删除值
            logic-not-delete-value: 0 # 逻辑未删除值

jwt:
    secret-key: 6218afc7dc5353dbad602c8f3227ab06dfa9e6c9471c2449fa132d7bc7e959ab