server:
    port: ${SERVER_PORT:8080}

spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
        host: ${SPRING_REDIS_HOST}
        port: ${SPRING_REDIS_PORT}
        #        password: your_redis_password  # 如果有密码的话
        database: 0
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                min-idle: 0
                max-wait: -1ms
logging:
    level:
        org:
            zalando:
                logbook: TRACE

user:
    dir: ${PROJECT_DIR}


mybatis-plus:
    global-config:
        db-config:
            logic-delete-field: is_deleted # 全局逻辑删除字段名
            logic-delete-value: 1 # 逻辑已删除值
            logic-not-delete-value: 0 # 逻辑未删除值

jwt:
    secret-key: ${JWT_SECRET}

springdoc:
    swagger-ui:
        path: /api/v1/swagger/swagger-ui.html
    api-docs:
        path: /api/v1/swagger/api-docs


